# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: bcrypt

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_MODERATOR:  [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_ADMIN:  [ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
          - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # comment it when using acl

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            simple_preauth:
                 authenticator: api_token_authenticator

        admin:
            pattern:  /
            context:  user
            form_login:
                provider:  fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path:  /admin/login
                use_forward:  false
                check_path:  /admin/login_check
                failure_path:  null
            logout:
                path:  /admin/logout
            anonymous:  true

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

       # Secured part of the site
       # This config requires being logged for the whole site
       # and having the admin role for the admin part.
       # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # API
        - { path: ^/api/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/sign_in, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/validate_token, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, role: IS_AUTHENTICATED_ANONYMOUSLY }
